from pathlib import Path


WIDTH, HEIGHT = 1200, 600
BRIDGE_WORLD_WIDTH = 3600
NAFPAKTOS_WORLD_WIDTH = BRIDGE_WORLD_WIDTH
NAFPAKTOS_CASTLE_X = NAFPAKTOS_WORLD_WIDTH - 540 - 180
MOUNTAIN_RIVER_WORLD_WIDTH = 3000
FERRY_BOAT_WORLD_WIDTH = 3000
PATRAS_CITY_WORLD_WIDTH = 3300
SCHOOL_WORLD_WIDTH = 2000
CLASSROOM_WORLD_WIDTH = 1200
SICK_APATOSAURUS_X = MOUNTAIN_RIVER_WORLD_WIDTH - 580
ROCKY_BARRIER_X = SICK_APATOSAURUS_X + 308
STONE_BRIDGE_DECK_Y = 272
FPS = 60
ROAD_TOP = 485
GROUND_Y = ROAD_TOP - 66
SKY = (123, 202, 235)
ROAD = (48, 52, 58)
MAX_HEALTH = 3

SPRITES_DIR = Path(__file__).with_name("sprites")
RUN_FRAME_PATHS = (
    SPRITES_DIR / "dinoa.png",
    SPRITES_DIR / "dinob.png",
)
CROUCH_FRAME_PATH = SPRITES_DIR / "couching.png"
MEAT_IMAGE_PATH = SPRITES_DIR / "meat.png"
BOTTLE_IMAGE_PATH = SPRITES_DIR / "bottle.png"
WEAPON_IMAGE_PATH = SPRITES_DIR / "weapon.png"
HEART_IMAGE_PATH = SPRITES_DIR / "heart.png"
SLEEPING_APATOSAURUS_IMAGE_PATH = SPRITES_DIR / "apatosaurousSleeping.png"
AWAKE_APATOSAURUS_IMAGE_PATH = SPRITES_DIR / "apatosaurousUp.png"
LOCHNESS_IMAGE_PATH = SPRITES_DIR / "lochness.png"
MONSTER_NECK_IMAGE_PATH = SPRITES_DIR / "monsterneck.png"
VELOCIRAPTOR_FRAME_PATHS = (
    SPRITES_DIR / "velociraptor1.png",
    SPRITES_DIR / "velociraptor2.png",
)

RESOURCE_TARGETS = {"meat": 3, "water": 3, "weapon": 3}
RESOURCE_WIDTHS = {"meat": 40, "water": 52, "weapon": 45}
RESOURCE_IMAGE_PATHS = {
    "meat": MEAT_IMAGE_PATH,
    "water": BOTTLE_IMAGE_PATH,
    "weapon": WEAPON_IMAGE_PATH,
    "heart": HEART_IMAGE_PATH,
}
